//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class db_mvctourismEntities : DbContext
    {
        public db_mvctourismEntities()
            : base("name=db_mvctourismEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Booking> tbl_Booking { get; set; }
        public DbSet<tbl_District> tbl_District { get; set; }
        public DbSet<tbl_Feedback> tbl_Feedback { get; set; }
        public DbSet<tbl_Hotel> tbl_Hotel { get; set; }
        public DbSet<tbl_Room> tbl_Room { get; set; }
        public DbSet<tbl_Tax> tbl_Tax { get; set; }
        public DbSet<tbl_TouristPlaces> tbl_TouristPlaces { get; set; }
        public DbSet<tbl_UserRegistration> tbl_UserRegistration { get; set; }
    
        public virtual ObjectResult<sp_GetallPlaces_Result> sp_GetallPlaces()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetallPlaces_Result>("sp_GetallPlaces");
        }
    
        public virtual ObjectResult<string> sp_UserReg(string name, string address, string email, string phone, string image, string uname, string pswd, Nullable<System.DateTime> cdate, Nullable<System.DateTime> udate, string status)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            var cdateParameter = cdate.HasValue ?
                new ObjectParameter("cdate", cdate) :
                new ObjectParameter("cdate", typeof(System.DateTime));
    
            var udateParameter = udate.HasValue ?
                new ObjectParameter("udate", udate) :
                new ObjectParameter("udate", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_UserReg", nameParameter, addressParameter, emailParameter, phoneParameter, imageParameter, unameParameter, pswdParameter, cdateParameter, udateParameter, statusParameter);
        }
    }
}
