//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tax
    {
        public int Id { get; set; }
        public Nullable<int> fk_Districtid { get; set; }
        public Nullable<int> fk_Roomid { get; set; }
        public string Tax { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Status { get; set; }
    
        public virtual tbl_District tbl_District { get; set; }
        public virtual tbl_Room tbl_Room { get; set; }
    }
}
