//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Booking
    {
        public int Id { get; set; }
        public int fk_UserId { get; set; }
        public int fk_placeid { get; set; }
        public int fk_hotelid { get; set; }
        public int fk_roomid { get; set; }
        public System.DateTime Created_date { get; set; }
        public System.DateTime Updated_date { get; set; }
        public string status { get; set; }
    
        public virtual tbl_Hotel tbl_Hotel { get; set; }
        public virtual tbl_Room tbl_Room { get; set; }
        public virtual tbl_TouristPlaces tbl_TouristPlaces { get; set; }
        public virtual tbl_UserRegistration tbl_UserRegistration { get; set; }
    }
}
