//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TouristPlaces
    {
        public tbl_TouristPlaces()
        {
            this.tbl_Booking = new HashSet<tbl_Booking>();
            this.tbl_Hotel = new HashSet<tbl_Hotel>();
        }
    
        public int Id { get; set; }
        public int Fk_Districtid { get; set; }
        public string Places { get; set; }
        public string Discription { get; set; }
        public string Nearesr_Place { get; set; }
        public string Image { get; set; }
        public System.DateTime Created_date { get; set; }
        public System.DateTime Updated_date { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<tbl_Booking> tbl_Booking { get; set; }
        public virtual tbl_District tbl_District { get; set; }
        public virtual ICollection<tbl_Hotel> tbl_Hotel { get; set; }
    }
}
