//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ThirdMethod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int studentId { get; set; }
        public string name { get; set; }
        public string eMail { get; set; }
        public string password { get; set; }
        public string course { get; set; }
        public string district { get; set; }
        public string gender { get; set; }
    }
}
